class SuraModel {
  final int suraNum;
  final String suraNameAr;
  final String suraNameEn;
  final int versesNum;

  const SuraModel({
    required this.suraNum,
    required this.suraNameAr,
    required this.suraNameEn,
    required this.versesNum,
  });
  static const List<SuraModel> allSurahs = [
    SuraModel(suraNum: 1, suraNameAr: "الفاتحه", suraNameEn: "Al-Fatiha", versesNum: 7),
    SuraModel(suraNum: 2, suraNameAr: "البقرة", suraNameEn: "Al-Baqarah", versesNum: 286),
    SuraModel(suraNum: 3, suraNameAr: "آل عمران", suraNameEn: "Aal-E-Imran", versesNum: 200),
    SuraModel(suraNum: 4, suraNameAr: "النساء", suraNameEn: "An-Nisa'", versesNum: 176),
    SuraModel(suraNum: 5, suraNameAr: "المائدة", suraNameEn: "Al-Ma'idah", versesNum: 120),
    SuraModel(suraNum: 6, suraNameAr: "الأنعام", suraNameEn: "Al-An'am", versesNum: 165),
    SuraModel(suraNum: 7, suraNameAr: "الأعراف", suraNameEn: "Al-A'raf", versesNum: 206),
    SuraModel(suraNum: 8, suraNameAr: "الأنفال", suraNameEn: "Al-Anfal", versesNum: 75),
    SuraModel(suraNum: 9, suraNameAr: "التوبة", suraNameEn: "At-Tawbah", versesNum: 129),
    SuraModel(suraNum: 10, suraNameAr: "يونس", suraNameEn: "Yunus", versesNum: 109),
    SuraModel(suraNum: 11, suraNameAr: "هود", suraNameEn: "Hud", versesNum: 123),
    SuraModel(suraNum: 12, suraNameAr: "يوسف", suraNameEn: "Yusuf", versesNum: 111),
    SuraModel(suraNum: 13, suraNameAr: "الرعد", suraNameEn: "Ar-Ra'd", versesNum: 43),
    SuraModel(suraNum: 14, suraNameAr: "إبراهيم", suraNameEn: "Ibrahim", versesNum: 52),
    SuraModel(suraNum: 15, suraNameAr: "الحجر", suraNameEn: "Al-Hijr", versesNum: 99),
    SuraModel(suraNum: 16, suraNameAr: "النحل", suraNameEn: "An-Nahl", versesNum: 128),
    SuraModel(suraNum: 17, suraNameAr: "الإسراء", suraNameEn: "Al-Isra", versesNum: 111),
    SuraModel(suraNum: 18, suraNameAr: "الكهف", suraNameEn: "Al-Kahf", versesNum: 110),
    SuraModel(suraNum: 19, suraNameAr: "مريم", suraNameEn: "Maryam", versesNum: 98),
    SuraModel(suraNum: 20, suraNameAr: "طه", suraNameEn: "Ta-Ha", versesNum: 135),
    SuraModel(suraNum: 21, suraNameAr: "الأنبياء", suraNameEn: "Al-Anbiya", versesNum: 112),
    SuraModel(suraNum: 22, suraNameAr: "الحج", suraNameEn: "Al-Hajj", versesNum: 78),
    SuraModel(suraNum: 23, suraNameAr: "المؤمنون", suraNameEn: "Al-Mu'minun", versesNum: 118),
    SuraModel(suraNum: 24, suraNameAr: "النّور", suraNameEn: "An-Nur", versesNum: 64),
    SuraModel(suraNum: 25, suraNameAr: "الفرقان", suraNameEn: "Al-Furqan", versesNum: 77),
    SuraModel(suraNum: 26, suraNameAr: "الشعراء", suraNameEn: "Ash-Shu'ara", versesNum: 227),
    SuraModel(suraNum: 27, suraNameAr: "النّمل", suraNameEn: "An-Naml", versesNum: 93),
    SuraModel(suraNum: 28, suraNameAr: "القصص", suraNameEn: "Al-Qasas", versesNum: 88),
    SuraModel(suraNum: 29, suraNameAr: "العنكبوت", suraNameEn: "Al-Ankabut", versesNum: 69),
    SuraModel(suraNum: 30, suraNameAr: "الرّوم", suraNameEn: "Ar-Rum", versesNum: 60),
    SuraModel(suraNum: 31, suraNameAr: "لقمان", suraNameEn: "Luqman", versesNum: 34),
    SuraModel(suraNum: 32, suraNameAr: "السجدة", suraNameEn: "As-Sajda", versesNum: 30),
    SuraModel(suraNum: 33, suraNameAr: "الأحزاب", suraNameEn: "Al-Ahzab", versesNum: 73),
    SuraModel(suraNum: 34, suraNameAr: "سبأ", suraNameEn: "Saba", versesNum: 54),
    SuraModel(suraNum: 35, suraNameAr: "فاطر", suraNameEn: "Fatir", versesNum: 45),
    SuraModel(suraNum: 36, suraNameAr: "يس", suraNameEn: "Ya-Sin", versesNum: 83),
    SuraModel(suraNum: 37, suraNameAr: "الصافات", suraNameEn: "As-Saffat", versesNum: 182),
    SuraModel(suraNum: 38, suraNameAr: "ص", suraNameEn: "Sad", versesNum: 88),
    SuraModel(suraNum: 39, suraNameAr: "الزمر", suraNameEn: "Az-Zumar", versesNum: 75),
    SuraModel(suraNum: 40, suraNameAr: "غافر", suraNameEn: "Ghafir", versesNum: 85),
    SuraModel(suraNum: 41, suraNameAr: "فصّلت", suraNameEn: "Fussilat", versesNum: 54),
    SuraModel(suraNum: 42, suraNameAr: "الشورى", suraNameEn: "Ash-Shura", versesNum: 53),
    SuraModel(suraNum: 43, suraNameAr: "الزخرف", suraNameEn: "Az-Zukhruf", versesNum: 89),
    SuraModel(suraNum: 44, suraNameAr: "الدّخان", suraNameEn: "Ad-Dukhan", versesNum: 59),
    SuraModel(suraNum: 45, suraNameAr: "الجاثية", suraNameEn: "Al-Jathiya", versesNum: 37),
    SuraModel(suraNum: 46, suraNameAr: "الأحقاف", suraNameEn: "Al-Ahqaf", versesNum: 35),
    SuraModel(suraNum: 47, suraNameAr: "محمد", suraNameEn: "Muhammad", versesNum: 38),
    SuraModel(suraNum: 48, suraNameAr: "الفتح", suraNameEn: "Al-Fath", versesNum: 29),
    SuraModel(suraNum: 49, suraNameAr: "الحجرات", suraNameEn: "Al-Hujurat", versesNum: 18),
    SuraModel(suraNum: 50, suraNameAr: "ق", suraNameEn: "Qaf", versesNum: 45),
    SuraModel(suraNum: 51, suraNameAr: "الذاريات", suraNameEn: "Adh-Dhariyat", versesNum: 60),
    SuraModel(suraNum: 52, suraNameAr: "الطور", suraNameEn: "At-Tur", versesNum: 49),
    SuraModel(suraNum: 53, suraNameAr: "النجم", suraNameEn: "An-Najm", versesNum: 62),
    SuraModel(suraNum: 54, suraNameAr: "القمر", suraNameEn: "Al-Qamar", versesNum: 55),
    SuraModel(suraNum: 55, suraNameAr: "الرحمن", suraNameEn: "Ar-Rahman", versesNum: 78),
    SuraModel(suraNum: 56, suraNameAr: "الواقعة", suraNameEn: "Al-Waqi'a", versesNum: 96),
    SuraModel(suraNum: 57, suraNameAr: "الحديد", suraNameEn: "Al-Hadid", versesNum: 29),
    SuraModel(suraNum: 58, suraNameAr: "المجادلة", suraNameEn: "Al-Mujadila", versesNum: 22),
    SuraModel(suraNum: 59, suraNameAr: "الحشر", suraNameEn: "Al-Hashr", versesNum: 24),
    SuraModel(suraNum: 60, suraNameAr: "الممتحنة", suraNameEn: "Al-Mumtahina", versesNum: 13),
    SuraModel(suraNum: 61, suraNameAr: "الصف", suraNameEn: "As-Saff", versesNum: 14),
    SuraModel(suraNum: 62, suraNameAr: "الجمعة", suraNameEn: "Al-Jumu'a", versesNum: 11),
    SuraModel(suraNum: 63, suraNameAr: "المنافقون", suraNameEn: "Al-Munafiqun", versesNum: 11),
    SuraModel(suraNum: 64, suraNameAr: "التغابن", suraNameEn: "At-Taghabun", versesNum: 18),
    SuraModel(suraNum: 65, suraNameAr: "الطلاق", suraNameEn: "At-Talaq", versesNum: 12),
    SuraModel(suraNum: 66, suraNameAr: "التحريم", suraNameEn: "At-Tahrim", versesNum: 12),
    SuraModel(suraNum: 67, suraNameAr: "الملك", suraNameEn: "Al-Mulk", versesNum: 30),
    SuraModel(suraNum: 68, suraNameAr: "القلم", suraNameEn: "Al-Qalam", versesNum: 52),
    SuraModel(suraNum: 69, suraNameAr: "الحاقة", suraNameEn: "Al-Haqqah", versesNum: 52),
    SuraModel(suraNum: 70, suraNameAr: "المعارج", suraNameEn: "Al-Ma'arij", versesNum: 44),
    SuraModel(suraNum: 71, suraNameAr: "نوح", suraNameEn: "Nuh", versesNum: 28),
    SuraModel(suraNum: 72, suraNameAr: "الجن", suraNameEn: "Al-Jinn", versesNum: 28),
    SuraModel(suraNum: 73, suraNameAr: "المزّمّل", suraNameEn: "Al-Muzzammil", versesNum: 20),
    SuraModel(suraNum: 74, suraNameAr: "المدّثر", suraNameEn: "Al-Muddathir", versesNum: 56),
    SuraModel(suraNum: 75, suraNameAr: "القيامة", suraNameEn: "Al-Qiyamah", versesNum: 40),
    SuraModel(suraNum: 76, suraNameAr: "الإنسان", suraNameEn: "Al-Insan", versesNum: 31),
    SuraModel(suraNum: 77, suraNameAr: "المرسلات", suraNameEn: "Al-Mursalat", versesNum: 50),
    SuraModel(suraNum: 78, suraNameAr: "النبأ", suraNameEn: "An-Naba'", versesNum: 40),
    SuraModel(suraNum: 79, suraNameAr: "النازعات", suraNameEn: "An-Nazi'at", versesNum: 46),
    SuraModel(suraNum: 80, suraNameAr: "عبس", suraNameEn: "Abasa", versesNum: 42),
    SuraModel(suraNum: 81, suraNameAr: "التكوير", suraNameEn: "At-Takwir", versesNum: 29),
    SuraModel(suraNum: 82, suraNameAr: "الإنفطار", suraNameEn: "Al-Infitar", versesNum: 19),
    SuraModel(suraNum: 83, suraNameAr: "المطفّفين", suraNameEn: "Al-Mutaffifin", versesNum: 36),
    SuraModel(suraNum: 84, suraNameAr: "الإنشقاق", suraNameEn: "Al-Inshiqaq", versesNum: 25),
    SuraModel(suraNum: 85, suraNameAr: "البروج", suraNameEn: "Al-Buruj", versesNum: 22),
    SuraModel(suraNum: 86, suraNameAr: "الطارق", suraNameEn: "At-Tariq", versesNum: 17),
    SuraModel(suraNum: 87, suraNameAr: "الأعلى", suraNameEn: "Al-A'la", versesNum: 19),
    SuraModel(suraNum: 88, suraNameAr: "الغاشية", suraNameEn: "Al-Ghashiyah", versesNum: 26),
    SuraModel(suraNum: 89, suraNameAr: "الفجر", suraNameEn: "Al-Fajr", versesNum: 30),
    SuraModel(suraNum: 90, suraNameAr: "البلد", suraNameEn: "Al-Balad", versesNum: 20),
    SuraModel(suraNum: 91, suraNameAr: "الشمس", suraNameEn: "Ash-Shams", versesNum: 15),
    SuraModel(suraNum: 92, suraNameAr: "الليل", suraNameEn: "Al-Lail", versesNum: 21),
    SuraModel(suraNum: 93, suraNameAr: "الضحى", suraNameEn: "Ad-Duha", versesNum: 11),
    SuraModel(suraNum: 94, suraNameAr: "الشرح", suraNameEn: "Ash-Sharh", versesNum: 8),
    SuraModel(suraNum: 95, suraNameAr: "التين", suraNameEn: "At-Tin", versesNum: 5),
    SuraModel(suraNum: 96, suraNameAr: "العلق", suraNameEn: "Al-Alaq", versesNum: 19),
    SuraModel(suraNum: 97, suraNameAr: "القدر", suraNameEn: "Al-Qadr", versesNum: 5),
    SuraModel(suraNum: 98, suraNameAr: "البينة", suraNameEn: "Al-Bayyina", versesNum: 8),
    SuraModel(suraNum: 99, suraNameAr: "الزلزلة", suraNameEn: "Az-Zalzalah", versesNum: 8),
    SuraModel(suraNum: 100, suraNameAr: "العاديات", suraNameEn: "Al-Adiyat", versesNum: 11),
    SuraModel(suraNum: 101, suraNameAr: "القارعة", suraNameEn: "Al-Qari'a", versesNum: 11),
    SuraModel(suraNum: 102, suraNameAr: "التكاثر", suraNameEn: "At-Takathur", versesNum: 8),
    SuraModel(suraNum: 103, suraNameAr: "العصر", suraNameEn: "Al-Asr", versesNum: 3),
    SuraModel(suraNum: 104, suraNameAr: "الهمزة", suraNameEn: "Al-Humazah", versesNum: 9),
    SuraModel(suraNum: 105, suraNameAr: "الفيل", suraNameEn: "Al-Fil", versesNum: 5),
    SuraModel(suraNum: 106, suraNameAr: "قريش", suraNameEn: "Quraysh", versesNum: 4),
    SuraModel(suraNum: 107, suraNameAr: "الماعون", suraNameEn: "Al-Ma'un", versesNum: 6),
    SuraModel(suraNum: 108, suraNameAr: "الكوثر", suraNameEn: "Al-Kawthar", versesNum: 3),
    SuraModel(suraNum: 109, suraNameAr: "الكافرون", suraNameEn: "Al-Kafirun", versesNum: 6),
    SuraModel(suraNum: 110, suraNameAr: "النصر", suraNameEn: "An-Nasr", versesNum: 3),
    SuraModel(suraNum: 111, suraNameAr: "المسد", suraNameEn: "Al-Masad", versesNum: 5),
    SuraModel(suraNum: 112, suraNameAr: "الإخلاص", suraNameEn: "Al-Ikhlas", versesNum: 4),
    SuraModel(suraNum: 113, suraNameAr: "الفلق", suraNameEn: "Al-Falaq", versesNum: 5),
    SuraModel(suraNum: 114, suraNameAr: "الناس", suraNameEn: "An-Nas", versesNum: 6),
  ];
}